app: example-app
org: example-org
service: example-service

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: ap-southeast-2

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  server:
    handler: server.handler
    events:
      - http: GET /
    timeout: 10
    environment:
      POSTGRESQL_URL: ${env:POSTGRESQL_URL}
